defaults:
  - model: f # N2 # default
  - run_schedule: neco # hebb_conv_3 # different_timescales # gaussian_randint_field
  - _self_
  - override hydra/job_logging: default  # colorlog
  - override hydra/hydra_logging: default  #colorlog


hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}


name: Default
model_class: default


simulation:
  T: 700
  use_transients: false
  dt: 1  # Set to 1 as the base discretization step

max_size: 1e4
Js_size: 1e5 #${model.N} * ${model.N} * ${simulation.T}


skip_default: true

stationarity_analysis:
  enabled: false
  significance: 0.01
  window_size: 100
  min_periods: 600
  bins: 100

save:
  enabled: true
  folders:
    data: ${hydra:runtime.cwd}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}/data
    static_vis: "static_visualizations"
    dynamic_vis: "dynamic_visualizations"


visualizations:
  log_X: false
  static:
    # - neural_activities
    # # - synaptic_hebb_difference
    # # - synaptic_hebb_abs_difference
    # # - synaptic_hebb_norm_difference
    # # - synaptic_hebb_F_norm_difference
    # # - synaptic_weights
    # # - external_fields
    # # - final_distributions
    # - deltaFnorm2_kt
    # # - overlaps
    # # - energy
    # # - autocorrelation
    # # - stationarity
    - deltaFnorm2_kt_residuals 
    # - deltaFnorm2_kt_residuals_hist



  dynamic:
    # - neural_activities_gif
    # - synaptic_weights_gif
    # - synaptic_hebb_difference_gif
    # - phase_space_gif
    